### PR TITLE
build theses files  is a features requesting 

### PR DESCRIPTION
**Pull request by djibal**
git commit -m" add instructions for project and improve to (doc) and folder files git"

### CODE REVIEW

**Comment by djibal** [comment]
@djibbs /Pull safety pull request to identified error occurred for continuing solved building files in yml

**Comment by djibal** [comment]
Please [@djibbs @djibal] this (comment)to reach solution to solve un merged branch l.

**Comment by djibal** [comment]
remove all #20  duplicates phrases in the tags line h1

**Review by djibbs — APPROVED** [review]
It’s a large repository👀-All

**Comment by djibbs** [comment]
@djibal  helps needed to solved in (#20) and build -All

**Comment by djibal** [comment]
reopen with this comment to continueb to merged (#20) branch safely

**Review by djibal — COMMENTED** [review]
Trigger on actions in YML

**Comment by djibal** [comment]
Improve in by update current file added

**Pull request merged**
